defaults:
  - _self_
  - paths: paths
  - model: logreg
  - general: general
  - download: download
  - features: features
  - splitting: splitting
  - cross_val: cross_val
  - mlflow: mlflow

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  verbose: False
